# Change these first
owner: 11vyo # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: bw.imoyv.com
    url: https://bw.imoyv.com
    icon: https://raw.githubusercontent.com/11vyo/status/main/assets/bw.png
  - name: cloud.imoyv.com
    url: https://cloud.imoyv.com
    icon: https://raw.githubusercontent.com/11vyo/status/main/assets/cloud.png
  - name: code.imoyv.com
    url: https://code.imoyv.com
    icon: https://raw.githubusercontent.com/11vyo/status/main/assets/code.png
  - name: drop.imoyv.com
    url: https://drop.imoyv.com
    icon: https://raw.githubusercontent.com/11vyo/status/main/assets/drop.png
  - name: ssh.imoyv.com
    url: https://ssh.imoyv.com
    icon: https://raw.githubusercontent.com/11vyo/status/main/assets/ssh.png
  - name: imoyv.com
    url: https://imoyv.com
    icon: https://raw.githubusercontent.com/11vyo/status/main/assets/imoyv.png

i18n:
  footer: Powered by [GitHub Actions!]($REPO)

commitMessages:
  commitAuthorName: "11Vyom"
  commitAuthorEmail: "70464758+11Vyom@users.noreply.github.com"

status-website:
  cname: status.imoyv.com
  theme: night
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: status.imoyv.com
  introTitle: "**Status Page**"
  navbar:
    - title: Home
      href: /
    - title: Discord
      href: https://dsc.gg/mess
